SELECT
	JSON_ARRAYAGG(
		JSON_OBJECT(
			'id_event',
			`events`.`id_event`,
			'name_event',
			`events`.`name_event`,
			'category_data',
			JSON_EXTRACT(
				IFNULL(
					(
					SELECT
						(
							JSON_ARRAYAGG(
								JSON_OBJECT(
									'id_category',
									category_events.id_category,
									'name_category',
									category_events.name_category,
									'order_category',
									category_events.order_category,
									'icon',
									category_events.icon 
								) 
							) 
						) 
					FROM
						category_events 
					WHERE
						category_events.id_category = `events`.id_category 
					),
					'[]' 
				),
				'$' 
			),
			'quest_data',
			JSON_EXTRACT(
				IFNULL(
					(
					SELECT
						(
							JSON_ARRAYAGG(
								JSON_OBJECT(
									'id_quest',
									`quests`.`id_quest`,
									'name_quest',
									`quests`.`name_quest`,
									'lastname_quest',
									`quests`.`lastname_quest`,
									'description',
									`quests`.`description`,
									'url_imagen',
									`quests`.`url_imagen` 
								) 
							) 
						) 
					FROM
						`quests` 
					WHERE
						`quests`.`id_quest` = `events`.`id_quest` 
					),
					'[]' 
				),
				'$' 
			),
			'date_event',
			`events`.date_event,
			'hour_event',
			`events`.hour_event,
			'event_key',
			`events`.event_key 
		) 
	) 
FROM
	`events`